name: Race Cars
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2385
title: Race cars
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f5f1'
    - '#183169'
    - '#4877bb'
    - '#7f9fd0'
    - '#e4bc4a'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
